apiVersion: v1
kind: Service
metadata:
  name: phpipam
  namespace: infra-backend
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: phpipam