apiVersion: v1
kind: Service
metadata:
  name: shlink
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: shlink

---

apiVersion: v1
kind: Service
metadata:
  name: shlink-web
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: shlink-web