apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink
  template:
    metadata:
      labels:
        app: shlink
    spec:
      containers:
      - name: shlink
        image: ghcr.io/shlinkio/shlink
        env:
          - name: DEFAULT_DOMAIN
            value: "s.zikanwari.f5.si"
          - name: IS_HTTPS_ENABLED
            value: "false"
          - name: GEOLITE_LICENSE_KEY
            value: "vFoxNzQk8O6PilLp"
          - name: DB_DRIVER
            value: "mysql"
          - name: DB_USER
            value: "shlink"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: shlink
                key: dbpass
          - name: DB_HOST
            value: "database1-0.database1.infra-backend.svc.cluster.local"