apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink-web
  template:
    metadata:
      labels:
        app: shlink-web
    spec:
      containers:
      - name: shlink
        image: ghcr.io/shlinkio/shlink-web-client