apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database1
  namespace: infra-backend
spec:
  serviceName: database1
  replicas: 1
  selector:
    matchLabels:
      app: database1
  template:
    metadata:
      labels:
        app: database1
    spec:
      containers:
      - name: database1
        image: mariadb
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database1
                key: rootpass
        volumeMounts:
        - name: database1
          mountPath: /var/lib/mysql/
  volumeClaimTemplates:
  - metadata:
      name: database1
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: nfs-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: infra-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database1
  template:
    metadata:
      labels:
        app: database1
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
          - name: PMA_HOST
            value: "10.1.100.198"

---

apiVersion: v1
kind: Service
metadata:
  name: database1
  namespace: infra-backend
spec:
  type: LoadBalancer
  ports:
  - name: "mysql-port"
    protocol: "TCP"
    port: 3306
  - name: "myadmin"
    protocol: "TCP"
    port: 80
  selector:
    app: database1