apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx01
  template:
    metadata:
      labels:
        app: nginx01
    spec:
      containers:
      - name: nginx01
        image: registry.launchpencil.f5.si/nginx01
