apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx01
  namespace: default
spec:
  secretName: nginx01-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: launchpencil.f5.si
  dnsNames:
  - launchpencil.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zikanwari
  namespace: default
spec:
  secretName: zikanwari-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: zikanwari.f5.si
  dnsNames:
  - zikanwari.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud
  namespace: default
spec:
  secretName: nextcloud-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: cloud.launchpencil.f5.si
  dnsNames:
  - cloud.launchpencil.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio
  namespace: infra-backend
spec:
  secretName: minio-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: minio.launchpencil.f5.si
  dnsNames:
  - minio.launchpencil.f5.si
  
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pon
spec:
  secretName: pon-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: pon.zikanwari.f5.si
  dnsNames:
  - pon.zikanwari.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor
  namespace: harbor
spec:
  secretName: harbor-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "core.harbor.launchpencil.f5.si"
  - "notary.harbor.launchpencil.f5.si"

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: line
spec:
  secretName: line-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: line.zikanwari.f5.si
  dnsNames:
  - line.zikanwari.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shlink
spec:
  secretName: shlink-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: s.zikanwari.f5.si
  dnsNames:
  - s.zikanwari.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shlink-lp
spec:
  secretName: lp-shlink-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: s.launchpencil.f5.si
  dnsNames:
  - s.launchpencil.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multipart
spec:
  secretName: multipart-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: multipart.zikanwari.f5.si
  dnsNames:
  - multipart.zikanwari.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: misskey
spec:
  secretName: miisskey-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: misskey.launchpencil.f5.si
  dnsNames:
  - misskey.launchpencil.f5.si

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: app.zikanwari.f5.si
  dnsNames:
  - app.zikanwari.f5.si