apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zikanwari
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: zikan-auth
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zikanwari
            port:
              number: 80
  - host: pon.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pon
            port:
              number: 80
  - host: s.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shlink
            port:
              number: 80
  tls:
  - hosts:
    - zikanwari.f5.si
    secretName: zikanwari-tls
  - hosts:
    - pon.zikanwari.f5.si
    secretName: pon-tls
  - hosts:
    - s.zikanwari.f5.si
    secretName: shlink-tls