apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: "minio-web"
    protocol: "TCP"
    port: 80
    targetPort: 9090
  - name: "minio-api"
    protocol: "TCP"
    port: 9000
    targetPort: 9000
  selector:
    app: minio