apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: cloudflared
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: truenas
  namespace: cloudflared
subsets:
- addresses:
  - ip: 192.168.0.2
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: rocky
  namespace: cloudflared
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090

---

apiVersion: v1
kind: Endpoints
metadata:
  name: rocky
  namespace: cloudflared
subsets:
- addresses:
  - ip: 192.168.0.1
  ports:
  - protocol: TCP
    port: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: cloudflared
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: cloudflared
subsets:
- addresses:
  - ip: 192.168.101.11
  ports:
  - protocol: TCP
    port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: esxi
  namespace: cloudflared
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: esxi
  namespace: cloudflared
subsets:
- addresses:
  - ip: 192.168.101.1
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: bs2108m
  namespace: cloudflared
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: bs2108m
  namespace: cloudflared
subsets:
- addresses:
  - ip: 192.168.101.253
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: rtx1100
  namespace: cloudflared
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: rtx1100
  namespace: cloudflared
subsets:
- addresses:
  - ip: 192.168.101.254
  ports:
  - protocol: TCP
    port: 80