apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
spec:
  serviceName: nextcloud
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud
        volumeMounts:
        - name: nextcloud
          mountPath: /var/www/html/
        env:
          - name: OVERWRITEPROTOCOL
            value: "https"
          - name: MYSQL_DATABASE
            value: "nextcloud"
          - name: MYSQL_USER
            value: "nextcloud"
          - name: MYSQL_HOST
            value: "192.168.0.3"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud
                key: pass
  volumeClaimTemplates:
  - metadata:
      name: nextcloud
    spec:
      storageClassName: ssd-client
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 32Gi