apiVersion: v1
kind: Service
metadata:
  name: database-influxdb
spec:
  type: LoadBalancer
  ports:
  - name: "influxdb-port"
    protocol: "TCP"
    port: 8086
  selector:
    app: database-influxdb

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: LoadBalancer
  ports:
  - name: "myadmin"
    protocol: "TCP"
    port: 80
  selector:
    app: phpmyadmin