apiVersion: v1
kind: Service
metadata:
  name: database1
  namespace: infra-backend
spec:
  type: LoadBalancer
  ports:
  - name: "mysql-port"
    protocol: "TCP"
    port: 3306
  - name: "myadmin"
    protocol: "TCP"
    port: 80
  selector:
    app: database1