
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: infra-backend
data:
  config.yaml: |
    tunnel: manage
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: pve.launchpencil.site
      service: https://192.168.101.11:8006
      originRequest:
          noTLSVerify: true
    - hostname: rtx.launchpencil.site
      service: http://192.168.108.254
    - hostname: rocky.launchpencil.site
      service: https://192.168.0.1:9090
      originRequest:
          noTLSVerify: true
    - hostname: nas.launchpencil.site
      service: http://192.168.0.2
    - hostname: esxi.launchpencil.site
      service: https://192.168.101.1
      originRequest:
          noTLSVerify: true
    - hostname: switch.launchpencil.site
      service: http://192.168.101.253
    - hostname: zabbix.launchpencil.site
      service: http://zabbix-server.monitor
    - hostname: dash.launchpencil.site
      service: https://kubernetes-dashboard.kubernetes-dashboard
      originRequest:
          noTLSVerify: true
    - hostname: argo.launchpencil.site
      service: https://argocd-server.argocd
      originRequest:
          noTLSVerify: true
    - hostname: db.launchpencil.site
      service: http://database1.infra-backend
    - hostname: grafana.launchpencil.site
      service: http://grafana.monitoring:3000
    - service: http_status:404