apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: cloudflared
  namespace: cloudflared
spec:
  ingressClassName: nginx-cf
  rules:
  - host: k8s.launchpencil.site
    http:
      paths:
      - path: /db
        pathType: Prefix
        backend:
          service:
            name: database
            port:
              number: 80
      - path: /dash
        pathType: Prefix
        backend:
          service:
            name: dashboard
            port:
              number: 80
      - path: /argo
        pathType: Prefix
        backend:
          service:
            name: argocd
            port:
              number: 80
      - path: /zabbix
        pathType: Prefix
        backend:
          service:
            name: zabbix
            port:
              number: 80