apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - maicoder.yaml
  - service.yaml
  - storage.yaml
images:
  - name: ghcr.io/omzh-scitechs/maicoder-api
    newName: ghcr.io/omzh-scitechs/maicoder-api
    newTag: sha-3dc2e49
  - name: ghcr.io/omzh-scitechs/maicoder-web
    newName: ghcr.io/omzh-scitechs/maicoder-web
    newTag: sha-08cb5a4
  - name: ghcr.io/omzh-scitechs/maicoder-web-template
    newName: ghcr.io/omzh-scitechs/maicoder-web-template
    newTag: sha-2db18a6
