apiVersion: apps/v1
kind: Deployment
metadata:
  name: maicoder-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maicoder-api
  template:
    metadata:
      labels:
        app: maicoder-api
    spec:
      containers:
      - name: maicoder-api
        image: ghcr.io/omzh-scitechs/maicoder:api
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/app/data"
          name: maicoder-pvc
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maicoder
              key: DB_PASSWORD
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: maicoder
              key: DB_USER
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: maicoder
              key: SECRET_KEY
      volumes:
      - name: maicoder-pvc
        persistentVolumeClaim:
          claimName: maicoder-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: maicoder-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maicoder-web
  template:
    metadata:
      labels:
        app: maicoder-web
    spec:
      containers:
      - name: maicoder-web
        image: ghcr.io/omzh-scitechs/maicoder:web
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: maicoder-web-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maicoder-web-template
  template:
    metadata:
      labels:
        app: maicoder-web-template
    spec:
      containers:
      - name: maicoder-web-template
        image: ghcr.io/omzh-scitechs/maicoder:web-template
        imagePullPolicy: Always

---