apiVersion: v1
kind: Service
metadata:
  name: maicoder-judge
spec:
  type: ClusterIP
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: maicoder-judge

---

apiVersion: v1
kind: Service
metadata:
  name: maicoder-web
spec:
  type: ClusterIP
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: maicoder-web