apiVersion: v1
kind: PersistentVolume
metadata:
  name: maicoder-pv
  labels:
    app: maicoder
spec:
  storageClassName: maicoder-stg
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.0.21
    path: /volume2/k8s/maicoder
  persistentVolumeReclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maicoder-pvc
  labels:
    app: maicoder
spec:
  storageClassName: maicoder-stg
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
