apiVersion: v1
kind: PersistentVolume
metadata:
  name: pon-pv
  labels:
    app: pon
spec:
  storageClassName: pon-stg
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.0.21
    path: /volume2/k8s/pon
  persistentVolumeReclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pon-pvc
  labels:
    app: pon
spec:
  storageClassName: pon-stg
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
