kind: Service
apiVersion: v1
metadata:
  name: zabbix-server
  namespace: monitor
  labels:
    app: zabbix-server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: snmp
    port: 162
    targetPort: 162
    protocol: TCP
  - name: snmp-udp
    port: 162
    targetPort: 162
    protocol: UDP
  - name: proxy
    port: 10051
    targetPort: 10051
  selector:
    app: zabbix-server

---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10050
    targetPort: 10050
    name: zabbix-agent
  selector:
    name: zabbix-agent