kind: Service
apiVersion: v1
metadata:
  name: zabbix-server
  namespace: monitor
  labels:
    app: zabbix-server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: snmp
    port: 162
    targetPort: 162
    protocol: TCP
  - name: snmp-udp
    port: 162
    targetPort: 162
    protocol: UDP
  - name: proxy
    port: 10051
    targetPort: 10051
  - name: proxy-udp
    port: 10051
    targetPort: 10051
    protocol: UDP
  selector:
    app: zabbix-server