kind: Service
apiVersion: v1
metadata:
  name: zabbix-server
  namespace: monitor
  labels:
    app: zabbix-server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: snmp
    port: 162
    targetPort: 162
  - name: snmp-udp
  - protocol: UDP
    port: 162
    targetPort: 162
  selector:
    app: zabbix-server