apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trap
  namespace: monitor
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: synology-iscsi-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mib
  namespace: monitor
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-client