apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql
        volumeMounts:
        - name: snmptraps
          mountPath: /var/lib/zabbix/snmptraps
        - name: mibs
          mountPath: /var/lib/zabbix/mibs
        env:
          - name: DB_SERVER_HOST
            value: "192.168.0.3"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: pass
          - name: ZBX_STARTVMWARECOLLECTORS
            value: "5"
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "true"
          - name: ZBX_ALLOWUNSUPPORTEDDBVERSIONS
            value: "1"
          - name: ZBX_CACHESIZE
            value: "128M"
          - name: ZBX_STARTPOLLERS
            value: "30"
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql
        env:
          - name: DB_SERVER_HOST
            value: "192.168.0.3"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: pass
      - name: zabbix-snmptraps
        image: zabbix/zabbix-snmptraps
        volumeMounts:
        - name: snmptraps
          mountPath: /var/lib/zabbix/snmptraps
        - name: mibs
          mountPath: /var/lib/zabbix/mibs
      volumes:
      - name: snmptraps
        persistentVolumeClaim:
          claimName: trap
      - name: mibs
        persistentVolumeClaim:
          claimName: mib

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: monitor
spec:
  selector:
    matchLabels:
      name: zabbix-agent
  template:
    metadata:
      labels:
        name: zabbix-agent
        app: zabbix
    spec:
      hostNetwork: true
      hostIPC: true
      hostPID: true
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent
          env:
            - name: ZBX_DENYKEY
              value: "system.run[*]"
            - name: ZBX_LOGREMOTECOMMANDS
              value: "1"
            - name: ZBX_SERVER_HOST
              value: "10.1.0.0/16"
            - name: ZBX_ACTIVE_ALLOW
              value: "false"
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZBX_UNSAFEUSERPARAMETERS
              value: "0"
          securityContext:
            capabilities: {}
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          volumeMounts:
            - name: dev-volume
              mountPath: /node/dev
            - name: procfs-volume
              readOnly: true
              mountPath: /node/proc
            - name: boot-volume
              readOnly: true
              mountPath: /node/boot
            - name: run-volume
              mountPath: /node/run
            - name: var-run-volume
              mountPath: /node/var/run
      volumes:
        - name: dev-volume
          hostPath:
            path: /dev
            type: ''
        - name: procfs-volume
          hostPath:
            path: /proc
            type: ''
        - name: boot-volume
          hostPath:
            path: /boot
            type: ''
        - name: run-volume
          hostPath:
            path: /run
            type: ''
        - name: var-run-volume
          hostPath:
            path: /var/run
            type: ''