apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql
        env:
          - name: DB_SERVER_HOST
            value: "10.1.100.198"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: pass
          - name: ZBX_STARTVMWARECOLLECTORS
            value: "5"
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql
        env:
          - name: DB_SERVER_HOST
            value: "database1-0.database1.infra-backend.svc.cluster.local"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: pass