apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql
        volumeMounts:
        - name: snmptraps
          mountPath: /var/lib/zabbix/snmptraps
        - name: mibs
          mountPath: /var/lib/zabbix/mibs
        env:
          - name: DB_SERVER_HOST
            value: "192.168.0.3"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: pass
          - name: ZBX_STARTVMWARECOLLECTORS
            value: "5"
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "true"
          - name: ZBX_ALLOWUNSUPPORTEDDBVERSIONS
            value: "1"
          - name: ZBX_CACHESIZE
            value: "128M"
          - name: ZBX_STARTPOLLERS
            value: "30"
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql
        env:
          - name: DB_SERVER_HOST
            value: "192.168.0.3"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-server
                key: pass
      - name: zabbix-snmptraps
        image: zabbix/zabbix-snmptraps
        volumeMounts:
        - name: snmptraps
          mountPath: /var/lib/zabbix/snmptraps
        - name: mibs
          mountPath: /var/lib/zabbix/mibs
      volumes:
      - name: snmptraps
        persistentVolumeClaim:
          claimName: trap
      - name: mibs
        persistentVolumeClaim:
          claimName: mib