apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynmap-mc01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynmap-mc01
  template:
    metadata:
      labels:
        app: dynmap-mc01
    spec:
      containers:
      - name: dynmap-mc01
        image: registry.launchpencil.f5.si/dynmap:mc01
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynmap-lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynmap-lobby
  template:
    metadata:
      labels:
        app: dynmap-lobby
    spec:
      containers:
      - name: dynmap-lobby
        image: registry.launchpencil.f5.si/dynmap:lobby
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynmap-sctech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynmap-sctech
  template:
    metadata:
      labels:
        app: dynmap-sctech
    spec:
      containers:
      - name: dynmap-sctech
        image: registry.launchpencil.f5.si/dynmap:sctech
        imagePullPolicy: Always