apiVersion: v1
kind: Service
metadata:
  name: mathattack
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: mathattack

---

apiVersion: v1
kind: Service
metadata:
  name: mathattack-rad
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: mathattack-rad