apiVersion: v1
kind: Service
metadata:
  name: dynmap-mc01
spec:
  type: ClusterIP
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: dynmap-mc01

---

apiVersion: v1
kind: Service
metadata:
  name: dynmap-lobby
spec:
  type: ClusterIP
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: dynmap-lobby

---

apiVersion: v1
kind: Service
metadata:
  name: dynmap-sctech
spec:
  type: ClusterIP
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: dynmap-sctech