apiVersion: apps/v1
kind: Deployment
metadata:
  name: zikanwari-api
spec:
  replicas: 0
  selector:
    matchLabels:
      app: zikanwari-api
  template:
    metadata:
      labels:
        app: zikanwari-api
    spec:
      containers:
      - name: zikanwari-api
        image: ghcr.io/zikanwari/zikanwari:api
        imagePullPolicy: Always
        env:
          - name: DB
            value: "192.168.0.3"