apiVersion: batch/v1
kind: CronJob
metadata:
  name: kadai-push
spec:
  schedule: "0 20 * * 0-4" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: zikan-push-job
            image: ghcr.io/zikanwari/zikanwari:push
            env:
            - name: publickey
              valueFrom:
              secretKeyRef:
                name: zikanwari
                key: publickey
            - name: privatekey
              valueFrom:
              secretKeyRef:
                name: zikanwari
                key: privatekey
            - name: user
              valueFrom:
              secretKeyRef:
                name: zikanwari
                key: user
            - name: pass
              valueFrom:
              secretKeyRef:
                name: zikanwari
                key: pass
          restartPolicy: OnFailure 