apiVersion: batch/v1
kind: CronJob
metadata:
  name: nikka-push
  namespace: zikanwari
spec:
  schedule: "0 11 * * 0-4" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nikka-push-job
            image: ghcr.io/zikanwari/zikanwari:nikka_push
            imagePullPolicy: Always
            env:
            - name: publickey
              valueFrom:
                secretKeyRef:
                  name: zikanwari
                  key: publickey
            - name: privatekey
              valueFrom:
                secretKeyRef:
                  name: zikanwari
                  key: privatekey
            - name: user
              valueFrom:
                secretKeyRef:
                  name: zikanwari
                  key: user
            - name: pass
              valueFrom:
                secretKeyRef:
                  name: zikanwari
                  key: pass
          restartPolicy: OnFailure 

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: kadai-push
spec:
  schedule: "5 11 * * 0-4" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kadai-push-job
            image: ghcr.io/zikanwari/zikanwari:kadai_push
            imagePullPolicy: Always
            env:
            - name: publickey
              valueFrom:
                secretKeyRef:
                  name: zikanwari
                  key: publickey
            - name: privatekey
              valueFrom:
                secretKeyRef:
                  name: zikanwari
                  key: privatekey
            - name: user
              valueFrom:
                secretKeyRef:
                  name: zikanwari
                  key: user
            - name: pass
              valueFrom:
                secretKeyRef:
                  name: zikanwari
                  key: pass
          restartPolicy: OnFailure 