apiVersion: batch/v1
kind: CronJob
metadata:
  name: kadai-push
spec:
  schedule: "0 20 * * 0-4" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: zikan-push-job
            image: ghcr.io/zikanwari/zikanwari:push
          restartPolicy: OnFailure 