apiVersion: v1
kind: Service
metadata:
  name: zikanwari
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: zikanwari

---

apiVersion: v1
kind: Service
metadata:
  name: zikanwari-line
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: zikanwari-line