apiVersion: apps/v1
kind: Deployment
metadata:
  name: zikanwari
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zikanwari
  template:
    metadata:
      labels:
        app: zikanwari
    spec:
      containers:
      - name: zikanwari
        image: registry.launchpencil.f5.si/zikanwari
        env:
          - name: DB
            value: "database1-0.database1.infra-backend.svc.cluster.local"
          - name: USER
            valueFrom:
              secretKeyRef:
                name: zikanwari
                key: user
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: zikanwari
                key: pass