apiVersion: apps/v1
kind: Deployment
metadata:
  name: zikanwari
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zikanwari
  template:
    metadata:
      labels:
        app: zikanwari
    spec:
      containers:
      - name: zikanwari-web
        image: ghcr.io/launchpencil/zikanwari:web
        imagePullPolicy: Always
        env:
          - name: DB
            value: "database1-0.database1.infra-backend.svc.cluster.local"
          - name: USER
            valueFrom:
              secretKeyRef:
                name: zikanwari
                key: user
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: zikanwari
                key: pass
      - name: zikanwari-bot
        image: ghcr.io/launchpencil/zikanwari:bot
        imagePullPolicy: Always
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: zikanwari
                key: token
      - name: zikanwari-line
        image: ghcr.io/launchpencil/zikanwari:line
        imagePullPolicy: Always
        env:
          - name: LINE_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: zikanwari
                key: line