apiVersion: apps/v1
kind: Deployment
metadata:
  name: zikanwari
  namespace: zikanwari
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zikanwari
  template:
    metadata:
      labels:
        app: zikanwari
    spec:
      containers:
      - name: zikanwari-web
        image: ghcr.io/zikanwari/zikanwari:web
        imagePullPolicy: Always
        env:
          - name: DB
            value: "192.168.0.3"
          - name: USER
            valueFrom:
              secretKeyRef:
                name: zikanwari
                key: user
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: zikanwari
                key: pass