apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmusic
spec:
  replicas: 0
  selector:
    matchLabels:
      app: jmusic
  template:
    metadata:
      labels:
        app: jmusic
    spec:
      containers:
      - name: jmusic
        image: core.harbor.launchpencil.f5.si/k8s/jmusic
      - name: jmusic-zikan
        image: core.harbor.launchpencil.f5.si/k8s/jmusic:zikan
        imagePullPolicy: Always
      imagePullSecrets:
      - name: registry-harbor