apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpipam
  namespace: infra-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpipam
  template:
    metadata:
      labels:
        app: phpipam
    spec:
      containers:
      - name: www
        image: phpipam/phpipam-www
        env:
          - name: TZ
            value: "Asia/Tokyo"
          - name: IPAM_DATABASE_HOST
            value: "192.168.0.3"
          - name: IPAM_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: phpipam
                key: user
          - name: IPAM_DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: phpipam
                key: pass
          - name: IPAM_DATABASE_NAME
            value: "phpipam"
      - name: cron
        image: phpipam/phpipam-cron
        env:
          - name: TZ
            value: "Asia/Tokyo"
          - name: IPAM_DATABASE_HOST
            value: "192.168.0.3"
          - name: IPAM_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: phpipam
                key: user
          - name: IPAM_DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: phpipam
                key: pass
          - name: IPAM_DATABASE_NAME
            value: "phpipam"
