apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hutility.yaml
  - service.yaml
  - gtfs.yaml

images:
  - name: ghcr.io/zikanwari/hutility
    newName: ghcr.io/zikanwari/hutility
    newTag: v1.2.0
  - name: ghcr.io/zikanwari/hutility-docs
    newName: ghcr.io/zikanwari/hutility-docs
