apiVersion: v1
kind: Service
metadata:
  name: factorization-api
spec:
  type: ClusterIP
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: factorization-api