apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database1
spec:
  serviceName: database1
  replicas: 1
  selector:
    matchLabels:
      app: database1
  template:
    metadata:
      labels:
        app: database1
    spec:
      containers:
      - name: database1
        image: mariadb
        volumeMounts:
        - name: database1
          mountPath: /var/lib/mysql/
  volumeClaimTemplates:
  - metadata:
      name: database1
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: nfs-client

---

apiVersion: v1
kind: Service
metadata:
  name: database1
spec:
  type: LoadBalancer
  ports:
  - name: "mysql-port"
    protocol: "TCP"
    port: 3306
  selector:
    app: database1