apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql
          env:
            - name: DB_SERVER_HOST
              value: "database1.infra-backend.svc.cluster.local"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-server
                  key: pass