apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: dc01
  name: dc01
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/vm: dc01
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: dvdisk
          interfaces:
          - name: bridge-net
            bridge: {}
        resources:
          requests:
            memory: 1Gi
        evictionStrategy: LiveMigrateIfPossible
      networks:
        - name: bridge-net
          multus:
            networkName: default/bridge-1
      terminationGracePeriodSeconds: 60
      volumes:
      - name: dvdisk
        dataVolume:
          name: dc01