apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-update
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
           - name: dbupdater
             image: ghcr.io/launchpencil/todo:updater
             env:
               - name: MYSQL_USER
                 valueFrom:
                   secretKeyRef:
                     name: zikanwari
                     key: user
               - name: MYSQL_PASSWORD
                 valueFrom:
                   secretKeyRef:
                     name: zikanwari
                     key: pass
          restartPolicy: OnFailure