apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrdrop
  template:
    metadata:
      labels:
        app: qrdrop
    spec:
      containers:
      - name: qrdrop
        image: ghcr.io/zikanwari/qrdrop
        imagePullPolicy: Always
        env:
          - name: accesskey
            valueFrom:
              secretKeyRef:
                name: qrdrop
                key: akey
          - name: secretkey
            valueFrom:
              secretKeyRef:
                name: qrdrop
                key: skey