apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: misskey-postgresql
spec:
  selector:
    matchLabels:
      app: misskey-db
  serviceName: "misskey-postgresql"
  replicas: 1
  template:
    metadata:
      labels:
        app: misskey-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: misskey
                key: dbpass
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: misskey
                key: dbname
          - name: PGDATA
            value: "/var/lib/postgresql/data/db-file"
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data/db-file
  volumeClaimTemplates:
  - metadata:
      name: postgres
    spec:
      storageClassName: nfs-client
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi