apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: misskey-postgresql
spec:
  selector:
    matchLabels:
      app: misskey-db
  serviceName: "misskey-postgresql"
  replicas: 1
  template:
    metadata:
      labels:
        app: misskey-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi