apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misskey-redis
  template:
    metadata:
      labels:
        app: misskey-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine