apiVersion: v1
kind: Service
metadata:
  name: misskey-redis
spec:
  type: ClusterIP
  ports:
  - name: "redis"
    protocol: "TCP"
    port: 6379
  selector:
    app: misskey-redis

---

apiVersion: v1
kind: Service
metadata:
  name: misskey-postgres
spec:
  type: ClusterIP
  ports:
  - name: "postgres"
    protocol: "TCP"
    port: 5432
  selector:
    app: misskey-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: misskey
spec:
  type: ClusterIP
  ports:
  - name: "misskey"
    protocol: "TCP"
    port: 80
    targetport: 3000
  selector:
    app: misskey