apiVersion: v1
kind: Service
metadata:
  name: misskey-db
spec:
  type: ClusterIP
  ports:
  - name: "redis"
    protocol: "TCP"
    port: 6379
  - name: "postgres"
    protocol: "TCP"
    port: 5432
  selector:
    app: misskey-db