apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    ingress.kubernetes.io/configuration-snippet: "proxy_set_header Host $http_host;\nproxy_set_header
      X-Real-IP $remote_addr;\nproxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\nproxy_set_header X-Forwarded-Proto $scheme;"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/server-snippet: |-
      client_max_body_size 100G;
      server_tokens off;
  name: nginx01
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: line.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zikanwari-line
            port:
              number: 3000
  - host: app.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zikanwari-app
            port:
              number: 80
  - host: studybattle.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: studybattle-client
            port:
              number: 80
  - host: waitdisplay.zikanwari.f5.si
    http:
      paths:
      - path: /show
        pathType: Prefix
        backend:
          service:
            name: waitdisplay-show
            port:
              number: 80
  - host: waitdisplay.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: waitdisplay-client
            port:
              number: 80
  - host: mathattack.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mathattack
            port:
              number: 80
  - host: api.launchpencil.f5.si
    http:
      paths:
      - path: /zikanwari
        pathType: Prefix
        backend:
          service:
            name: zikanwari-api
            port:
              number: 80
  - host: api.launchpencil.f5.si
    http:
      paths:
      - path: /todo
        pathType: Prefix
        backend:
          service:
            name: todo-api
            port:
              number: 80
  - host: api.launchpencil.f5.si
    http:
      paths:
      - path: /waitdisplay
        pathType: Prefix
        backend:
          service:
            name: waitdisplay-server
            port:
              number: 80
  - host: api.launchpencil.f5.si
    http:
      paths:
      - path: /studybattle
        pathType: Prefix
        backend:
          service:
            name: studybattle-api
            port:
              number: 80
  - host: api.launchpencil.f5.si
    http:
      paths:
      - path: /factorization
        pathType: Prefix
        backend:
          service:
            name: factorization-api
            port:
              number: 80
  - host: minio.launchpencil.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port: 
              number: 9000
  - host: minio.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port: 
              number: 9000
  - host: test.launchpencil.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
  - host: msky.launchpencil.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: misskey
            port:
              number: 80
  - host: qrdrop.zikanwari.f5.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qrdrop
            port:
              number: 80  
  tls:
  - hosts:
    - line.zikanwari.f5.si
    secretName: line-tls
  - hosts:
    - app.zikanwari.f5.si
    secretName: app-tls
  - hosts:
    - waitdisplay.zikanwari.f5.si
    secretName: waitdisplay-tls
  - hosts:
    - mathattack.zikanwari.f5.si
    secretName: mathattack-tls
  - hosts:
    - api.launchpencil.f5.si
    secretName: api-tls
  - hosts:
    - test.launchpencil.f5.si
    secretName: test-tls
  - hosts:
    - studybattle.zikanwari.f5.si
    secretName: studybattle-tls
  - hosts:
    - msky.launchpencil.f5.si
    secretName: miisskey-tls
  - hosts:
    - minio.launchpencil.f5.si
    secretName: minio-tls
  - hosts:
    - minio.zikanwari.f5.si
    secretName: minio-zikan-tls
  - hosts:
    - qrdrop.zikanwari.f5.si
    secretName: qrdrop-tls